server:
    port: 8080
    servlet:
        context-path: /api
spring:
    application:
        name: api
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://postgres:5432/postgres
        username: postgres
        password: admin123
        jpa:
            database-platform: org.hibernate.dialect.PostgreSQLDialect
            hibernate:
                ddl-auto: none
    flyway:
        baselineOnMigrate: true
